name: Cloud Playwright Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/java:v1.49.0-noble
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Test
        run: xvfb-run mvn clean test -Dheadless=false
      
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results/
